server:
    port: 9092
    context-path: /ui
#    session:
#      cookie:
#        name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: itsnow
      clientSecret: itsnow
      accessTokenUri: http://localhost:18001/auth/oauth/token
      userAuthorizationUri: http://localhost:18001/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:18001/auth/user/me
spring:
  thymeleaf:
    cache: false